### ISSUE TITLE
Copy over content

### ISSUE THREAD

**Issue by DeniseSl22** [ammar257ammar/snorql-extended#2]
Hi Ammar,

When I'm working on a SPARQL query, I sometimes have multiple tabs open to connect several lines of individual queries together. Would it be possible when I duplicate the browser page itself, that the content of the query window is copied over too?

**Comment by ammar257ammar** [comment]
Dear Denise, 

What you are describing is already possible using the "Get Permalink" button that will generate a link which by clicking on, it opens a new tab with the query editor content similar to the current tab. I think this is the functionality that you are describing.

Otherwise, duplicating tabs with copying the forms field contents to the new tab is something out of the scope of the web application itself and handled through the browser. However, maybe there are already extensions developed to copy forms data over duplicated tabs (which they are vendor-specific for the browser like: Chrome, Firefox and Opera).

I will close you this issue now, but if you have another idea or the previously mentioned functionality does not fulfill your needs, please open a new issue with your suggestion/idea.

Thank you for your feedback ^_^

**Comment by DeniseSl22** [comment]
Hi @ammar257ammar ; thank you for checking! The "get permalink" button doesn't work for me, so that would be one thing to check. Second, maybe having a "hover over" explanation for the buttons would be nice? Or we could make a brief tutorial video explaining all options, which we add to the page (can you add a little box somewhere hosting a video on the site itself)? I think that would make the options more intuitive for users.
